// Core engine — zero framework dependencies
export { RuleBuilder, rule } from '../builder/index';
export { ValiValid } from '../validation/ValiValid';
export { setLocale, getLocale, getMessage } from '../i18n/index';
export type { Locale } from '../i18n/index';
export type {
    FieldValidationConfig,
    BuilderValidationConfig,
    FormErrors,
    SetState,
    ValidationsConfig,
    SyncRule,
    AsyncRule,
} from '../types/index';
export {
    TypeFile,
    FileSize,
    DateFormat,
    DateFormatExpressions,
} from '../types/index';
export { ValidationType } from '../validation/Validators';
export type {
    ValidationConfigRequired,
    ValidationConfigMinLength,
    ValidationConfigMaxLength,
    ValidationConfigExactLength,
    ValidationConfigEmail,
    ValidationConfigUrl,
    ValidationConfigAlpha,
    ValidationConfigAlphaNumeric,
    ValidationConfigLowerCase,
    ValidationConfigUpperCase,
    ValidationConfigNoWhitespace,
    ValidationConfigContains,
    ValidationConfigStartsWith,
    ValidationConfigEndsWith,
    ValidationConfigSlug,
    ValidationConfigPasswordStrength,
    ValidationConfigHexColor,
    ValidationConfigIPv4,
    ValidationConfigUUID,
    ValidationConfigJson,
    ValidationConfigPhone,
    ValidationConfigCreditCard,
    ValidationConfigPattern,
    ValidationConfigDigitsOnly,
    ValidationConfigNumberRange,
    ValidationConfigNumberPositive,
    ValidationConfigNumberNegative,
    ValidationConfigInteger,
    ValidationConfigMultipleOf,
    ValidationConfigDateFormat,
    ValidationConfigMinDate,
    ValidationConfigMaxDate,
    ValidationConfigFutureDate,
    ValidationConfigPastDate,
    ValidationConfigFileType,
    ValidationConfigFileSize,
    ValidationConfigFileDimensions,
    ValidationConfigImageAspectRatio,
    ValidationConfigImageMinDimensions,
    ValidationConfigImageMaxDimensions,
    ValidationConfigMatchField,
    ValidationConfigRequiredIf,
    ValidationConfigAsyncPattern,
    ValidationConfigGreaterThan,
    ValidationConfigLessThan,
    ValidationConfigPrecision,
    ValidationConfigDateAfter,
    ValidationConfigDateBefore,
    ValidationConfigOneOf,
    ValidationConfigNotMatchField,
    ValidationConfigRequiredUnless,
    ValidationConfigArrayMinLength,
    ValidationConfigArrayMaxLength,
    ValidationConfigArrayUnique,
    ValidationConfigArrayContains,
    ValidationConfigTime,
    ValidationConfigNoHTML,
    ValidationConfigIBAN,
    ValidationConfigPostalCode,
    ValidationConfigLatitude,
    ValidationConfigLongitude,
    ValidationConfigSemVer,
    ValidationConfigBase64,
    ValidationConfigNotOneOf,
    ValidationConfigIPv6,
    ValidationConfigMACAddress,
    ValidationConfigDataURI,
    ValidationConfigMimeType,
    ValidationConfigArrayItems,
    ValidationConfigDateRange,
} from '../validation/Validators';
